version: '3.3'
services:
  db:
    image: mysql:8.3.0
    restart: always
    environment:
      MYSQL_DATABASE: 'NiRi'
      MYSQL_ROOT_PASSWORD: 'niri2214'
    ports:
      - '3307:3306'
    volumes:
      - my-db:/var/lib/mysql
  app:
    image: niri:v1
    ports:
      - '3000:8081'
volumes:
  my-db: